### ISSUE TITLE
Where do we want to put the "paper as code" article?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/journal_information#12]

**Comment by davidlmobley** [comment]
I don't know. I was firing that one at you. :) I want to link to it from the "Why LiveCoMS" article, though, so we should figure it out. I'll put in a temporary link to it.

**Comment by davidlmobley** [comment]
Thinking about this more now that I have carefully read everything: It seems to me like it may belong on the GitHub Pages site.
