### ISSUE TITLE
Licensing and data processing

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/journal_information#20]
There some discussion for the need for licenses that allow the data to in preprints to be scraped and processed.  Need to think about licensing a bit more to make sure that we make it properly general. The current plan to have CC-BY 4.0 sounds good for now, will have to keep thinking about it.

**Comment by davidlmobley** [comment]
I presume you mean in the ACS session? Can you elaborate a little more? I can see there would be a need for preprints and other articles to be under a clear license which clearly allows processing/reuse so it is clear that data (and other info) can be scraped and processed. But are there other complexities here I'm missing?

**Comment by davidlmobley** [comment]
I think we've resolved this by recommending/strongly encouraging CC-BY in our official policy documents on livecomsjournal.github.io
