### ISSUE TITLE
What style references?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/journal_information#24]
Right now references are by author, date, rather than by number.  What would people prefer?  I feel like in chemistry, its usually (superscript number), so that might be what people are more familiar with.

**Comment by davidlmobley** [comment]
I like superscript number, though I tend to be inclined towards the policy eLife has, which is that they support any reference format as long as it contains certain key information (I think the info allows the reference to be uniquely and electronically linked to a specific citation). I don't see why we would need to be more specific than that other than providing a "default style" that we really like. If someone has a really strong preference to do it another way, why not?

**Comment by mrshirts** [comment]
I'd kind of like to have a single 'brand' for all of the document in the journal - generally a journal has a single visual image. Since we are providing templates and class files anyway, this should be pretty simple to do.

**Comment by davidlmobley** [comment]
True. I'm fine with that. And my favorite is certainly superscript numbers, in the order in which they were referenced (not alphabetical -- I hate that).

**Comment by mrshirts** [comment]
Switched to superscript (I think it's correctly alphabetized, but can check later).  Fix is in the article_templates repository.

**Comment by davidlmobley** [comment]
I did say, "NOT ALPHABETICAL".

**Comment by mrshirts** [comment]
I meant, correctly alphabetized, meaning NOT alphabetized.  Writing too quickly!
