### ISSUE TITLE
Contact email address in "About" section

### ISSUE THREAD

**Issue by justinGilmer** [livecomsjournal/journal_information#27]
The contact email address in the [About](http://www.livecomsjournal.org/about) section links to @mrshirts email address. However, on our github page, we have an email address for livecoms (livecoms@gmail.com).

Should this be updated, or is that email address serving some other purpose?

If so, I can quickly change that and make a pull request.

**Comment by davidlmobley** [comment]
I think we use `livecoms@gmail.com` for now, not Michael Shirts. We are working on a longer-term option but it is not in place yet.

**Comment by jchodera** [comment]
A google org may be useful for this.

**Comment by mrshirts** [comment]
I think what you describe is the long term plan (i.e. a G-suite subscription that interfaces with the domain name).  If you are thinking of something a bit different, let me know.  We should have this in place by the time we start accepting papers.

**Comment by davidlmobley** [comment]
I was going to update this to point to `managing@livecomsjournal.org` which is the Google org address which is now in place, but I don't appear to have the ability (that content isn't in this repo), so I've assigned this to @mrshirts .
