### ISSUE TITLE
Invalid https certificate

### ISSUE THREAD

**Issue by ptmerz** [livecomsjournal/journal_information#31]
The https certificate of livecomsjournal.org is not valid:

```
www.livecomsjournal.org uses an invalid security certificate. 

The certificate is only valid for the following names: *.scholasticahq.com, scholasticahq.com 

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
Related: https://github.com/livecomsjournal/livecomsjournal.github.io/pull/53

**Comment by mrshirts** [comment]
I've talked to them - they recognize the issue, say to use http for now, and they are looking into https
