### ISSUE TITLE
Fix editorial board info

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/journal_information#32]
As noted https://github.com/livecomsjournal/livecomsjournal.github.io/issues/63, the editorial board is not correct. (And the formatting is still not good).

I tried to address this in a PR recently but presumably @mrshirts still needs to propagate my new content or something; checking master now.

**Comment by davidlmobley** [comment]
@dmzuckerman - [this is what SHOULD be on the website](https://github.com/livecomsjournal/journal_information/blob/master/website_text/editorial_board.md) but I think Michael still has to propagate the changes to this page. Does it look correct here?

**Comment by dmzuckerman** [comment]
Did @mrshirts recruit Rommie to be lead for tutorials??
________________________________

**Comment by davidlmobley** [comment]
Ah, right, I was trying to check that and add it to this page but then got distracted in the middle. Let me investigate.

**Comment by davidlmobley** [comment]
Hmm, I can't find this in the notes. @mrshirts will have to address.

**Comment by mrshirts** [comment]
Rommie -- still thinking. I will check.  New editorial board info propagated.

**Comment by davidlmobley** [comment]
@mrshirts - new editorial board info is STILL not showing up on the website. For example, there should be formatting changes, and also Yuji Sugita should be added (as well as other changes).

I also just did #33 adding Amaro for tutorials

**Comment by mrshirts** [comment]
Whoops.  Try now, should be up.

**Comment by davidlmobley** [comment]
Thanks, that did it.
