### ISSUE TITLE
Add submission fee

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/journal_information#57]
Comment from twitter: The submission fee is not listed on livecomsjournal.org and should be. :)

**Comment by mrshirts** [comment]
Is having it on the github site enough, or should we put it on the landing web site about page as well?

**Comment by davidlmobley** [comment]
Probably both.

**Comment by dmzuckerman** [comment]
I agree

**Comment by mrshirts** [comment]
Addressed by PR #60.  I found that the Git Pages site already had the text.

**Comment by davidlmobley** [comment]
Thanks.
