### ISSUE TITLE
Typo in Zukerman affiliation (superscript 3 but not listed below)

### ISSUE THREAD

**Issue by slochower** [livecomsjournal/journal_information#58]
<img width="704" alt="screen shot 2017-12-05 at 10 03 04 am" src="https://user-images.githubusercontent.com/5393995/33622671-5ef22f96-d9a3-11e7-9c58-992e5a5f2f31.png">

(Not sure the issue belongs here.)

**Comment by slochower** [comment]
(Meant "Zuckerman" sorry!)

**Comment by davidlmobley** [comment]
Thanks,yes, perfect.

**Comment by dmzuckerman** [comment]
Good catch.  Also, OHSU changed its name a few years back to 
Oregon Health and Science University [add 'and' remove 's']

**Comment by mrshirts** [comment]
Fixed on the website.
