### ISSUE TITLE
Where to put reviewer information on the GitHub site.

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/journal_information#68]
Currently, we have:

https://livecomsjournal.github.io/policies/reviewer_information/

Which gives some reviewer information, but from the perspective of the editors.  I'd like to turn this page into an actual reviewer instruction page.  The biggest change will be to remove the sample letters, and maybe move them to journal_information repository (this one).  Note that the letter templates themselves are saved in Scholastica where they can automatically be inserted via email, and the copies here will serve as a place where we can discuss the templates 

I'm not sure we need to include the exact letters that we will use for invitation/declining/etc., as long as the information is communicated.  I don't think we are being less transparent not including the exact phrasing, and it looks a bit weird.

**Comment by dmzuckerman** [comment]
I agree with @mrshirts that it looks weird to have the letters there, going forward and it's not really policy info that needs to be public.

**Comment by mrshirts** [comment]
OK, sounds good.  I'm in the middle of revising all of the reviewer information, so there is an explicit section for authors (to let them know about the process in general) and for the reviewers (to give explicit instructions).  Will get that up later tonight.

**Comment by mrshirts** [comment]
OK, see #143 for this move.
